# NumPy

creating n stuff

In [ ]:
import numpy as np

a=np.array([[1,2,3],[6,7,8]])  # 2 rows and 3 columns

print(a)
print("")
print(a.shape)
print(type(a))   # n-dimensional array

[[1 2 3]
 [6 7 8]]

(2, 3)
<class 'numpy.ndarray'>


## Array

- a grid in space to store and retrive data


In [17]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [33]:
print(a)

[ 1  2 10  4  5  6]


In [30]:
a[2]


np.int64(3)

In [ ]:
print(a[2])  # Accessing the third element

3


#### changing element

In [32]:
print(a)
a[2]=10
print(a)

[1 2 3 4 5 6]
[ 1  2 10  4  5  6]


### slicing


In [29]:
print(a[:3])

[1 2 3]


- original array gets edited

In [27]:
a = np.array([1, 2, 3, 4, 5, 6])
b=a[1:4]
print(b)
b[2]=20
print(a)
print(b)

[2 3 4]
[ 1  2  3 20  5  6]
[ 2  3 20]


## Multi-Dimensional arrays (Matrices)



In [26]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a.shape)  # gives rows x columns

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


- columns always last
- rows always 2nd last

In [ ]:
print(a.ndim)  # gives number of dimensions

2


In [22]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.size)  # give total no of elements

12


### NOTE

- size = product of elements in each row

In [38]:
import math, numpy as np
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

b= (a.size == math.prod(a.shape))
print (b)

True
